### ISSUE TITLE
tsc: ledgerCheckCommand returns a result, so commander's .action() rejects it (TS2345 in cli.ts)

### ISSUE THREAD

**Issue by rizen** [Shufflewick/BoardSmith#297]
\`npx tsc --noEmit -p tsconfig.json\` went from 289 errors at 16d6df5f to 290 on main. The one new error:

\`\`\`
src/cli/cli.ts(367,11): error TS2345: Argument of type '(options?: { project?: string; json?: boolean; }) => Promise<LedgerCheckResult>' is not assignable to parameter of type '(...args: any[]) => void | Promise<void>'.
\`\`\`

Introduced by d7d4c8a6 (#293), which added \`ledgerCheckCommand\` in src/cli/commands/ledger-check.ts with return type \`Promise<LedgerCheckResult>\` and wired it straight into \`.action(...)\`. Commander actions must return \`void | Promise<void>\`. Nothing reads the returned result (the tests call \`ledgerCheck()\` for the result and only check \`process.exitCode\` on the command).

Fix: make \`ledgerCheckCommand\` return \`Promise<void>\`, like the other \`*Command\` functions (e.g. \`constraintCheckCommand\`). Done when the tsc count is back to 289 and the suite is green.

**Comment by rizen** [comment]
Fixed in merge 624ae81f. Two new tsc errors since 16d6df5f, same cause: a *Command function returned its result and was passed to commander's .action(), which expects void. (1) ledgerCheckCommand from d7d4c8a6 (#293): now returns Promise<void>; nothing read the result. (2) testStepCheckCommand from #290's merge 693e4a70, which landed while this was in progress: now returns Promise<void>, and its tests read the JSON report the command prints with --json. npx tsc --noEmit -p tsconfig.json on main is 289, identical by file+code+message to the 16d6df5f baseline. npx vitest run on main: 10521 passed.
